// <auto-generated />
using System;
using core_service.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace core_service.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260508000100_AddModerationControls")]
    partial class AddModerationControls
    {
    }
}